spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5433/university_db
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  flyway:
    baseline-on-migrate: true
  application:
    name: University Managing Application
server:
  port: 8081
