version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: university_db
